### PR TITLE
fix #325

### LINKED ISSUE #325: Update composer.json information
The package name and dependence refer to the vendor marco-c but now is on github on mozilla vendor.
Can be fixed asap?

### PR DESCRIPTION
**Pull request by Mte90**

### CODE REVIEW

**Comment by Mte90** [comment]
To use that fork in the meantime:

```
  "require": {
    "mozilla/wp-web-push": "dev-master"
  },
  "repositories": [
    {
      "url": "https://github.com/Mte90/wp-web-push",
      "type": "vcs"
    },
    {
      "url": "git@github.com:mozilla/wp-sw-manager.git",
      "type": "git"
    },
    {
      "url": "git@github.com:marco-c/wp-web-app-manifest-generator.git",
      "type": "git"
    },
  ],
```

**Comment by mykmelez** [comment]
@marco-c, @delapuente: Are either of you still maintaining this project?

**Comment by delapuente** [comment]
I'm the official maintainer but I was on vacation until yesterday. I'm catching up with e-mail right now.

**Comment by mykmelez** [comment]
> I'm the official maintainer but I was on vacation until yesterday. I'm catching up with e-mail right now.

@delapuente Welcome back, and thanks for the quick response! It isn't urgent, I just wanted to make sure it doesn't fall through the cracks. :-)

**Comment by marco-c** [comment]
The custom version of jwt is needed to support older versions of PHP.
If we switch to the official version we lose support for them (if we want to drop support, then we should update the checks in https://github.com/mozilla/wp-web-push/blob/master/wp-web-push/wp-web-push.php#L13).

**Comment by Mte90** [comment]
ok but we get an error on composer so i think that we need to fix that else it's impossible to use it.

**Comment by marco-c** [comment]
Of course, I'm not suggesting we shouldn't fix the issue 😄

**Pull request closed without merging**
